# Избранные предложения
### Получить список избранных предложений
GET http://localhost:5001/favorite/ HTTP/1.1
Content-Type: application/json
### Изменить статус избранного у предложения
POST http://localhost:5001/favorite/6532955b5da3fa262da1acf7/1 HTTP/1.1
Content-Type: application/json
