# Пользователь
### Зарегистрировать нового пользователя
POST http://localhost:5001/user/register HTTP/1.1
Content-Type: application/json

{
  "email": "keks@htmlacademy.ru",
  "avatarUrl": "test.jpg",
  "name": "Keks",
  "password": "keks123",
  "type": "regular"
}

### Авторизовать пользователя
POST http://localhost:5001/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks@htmlacademy.ru",
  "password": "keks123"
}

### Отправить изображение
POST http://localhost:5001/user/avatar/6548de2dcc8898e4387f26ef HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatarUrl"; filename="paris.jpeg"
Content-Type: image/jpeg

< /Users/av/Downloads/paris.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Проверить токен пользователя
GET http://localhost:5001/user/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAaHRtbGFjYWRlbXkucnUiLCJuYW1lIjoiS2VrcyIsImlkIjoiNjU0Y2NhMWE0M2VkYTk3MGI1YmJhMTRhIiwiaWF0IjoxNjk5NTQ0NDc2LCJleHAiOjE2OTk3MTcyNzZ9.E3ZIZQdndlKRwjnylzTdKWySG2f7C_0wThpFS8sC7QE

### Выход пользователя
DELETE http://localhost:5001/user/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAaHRtbGFjYWRlbXkucnUiLCJuYW1lIjoiS2VrcyIsImlkIjoiNjU0Y2NhMWE0M2VkYTk3MGI1YmJhMTRhIiwiaWF0IjoxNjk5NTQ0NDc2LCJleHAiOjE2OTk3MTcyNzZ9.E3ZIZQdndlKRwjnylzTdKWySG2f7C_0wThpFS8sC7QE

