# Предложения
### Получить список предложений
GET http://localhost:5001/offers HTTP/1.1
Content-Type: application/json

### Получить список из 100 предложений
GET http://localhost:5001/offers?limit=100 HTTP/1.1
Content-Type: application/json

### Получить детальную информацию по предложению с заданным offerId
GET http://localhost:5001/offers/6544f0440e50272e1c12f696 HTTP/1.1
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAaHRtbGFjYWRlbXkucnUiLCJuYW1lIjoiS2VrcyIsImlkIjoiNjU0OGRlMmRjYzg4OThlNDM4N2YyNmVmIiwiaWF0IjoxNjk5Mjc0NTMzLCJleHAiOjE2OTk0NDczMzN9.IzH18psFqy4TxEWG4P3fvak6zB3-kBytIsjFQ8miYNs
Content-Type: application/json

### Создание нового предложения
POST http://localhost:5001/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAaHRtbGFjYWRlbXkucnUiLCJuYW1lIjoiS2VrcyIsImlkIjoiNjU0OGRlMmRjYzg4OThlNDM4N2YyNmVmIiwiaWF0IjoxNjk5Mjc0NTMzLCJleHAiOjE2OTk0NDczMzN9.IzH18psFqy4TxEWG4P3fvak6zB3-kBytIsjFQ8miYNs
Content-Type: application/json

{
  "userId": "6533b70719c994f5a07a4b7c",
  "title": "The Tile House",
  "description": "I am happy to welcome you to my apartment in the city center! Yo!",
  "previewImage": "https://13.design.pages.academy/static/hotel/1.jpg",
  "postDate": "2023-05-01T12:01:01",
  "city": {
    "name": "Brussels",
    "location": {
      "latitude": 50.846557,
      "longitude": 4.351697
    }
  },
  "isPremium": false,
  "type": "Apartment",
  "bedrooms": 1,
  "maxAdults": 1,
  "price": 100,
  "location": {
    "latitude": 50.836557,
    "longitude": 4.341697
  },
  "goods": [
      "Breakfast",
      "Washer"
    ],
  "photos": [ "https://13.design.pages.academy/static/hotel/1.jpg" ]
}

### Редактирование предложения
PATCH http://localhost:5001/offers/6548e0facc8898e4387f2714 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAaHRtbGFjYWRlbXkucnUiLCJuYW1lIjoiS2VrcyIsImlkIjoiNjU0OGRlMmRjYzg4OThlNDM4N2YyNmVmIiwiaWF0IjoxNjk5Mjc0NTMzLCJleHAiOjE2OTk0NDczMzN9.IzH18psFqy4TxEWG4P3fvak6zB3-kBytIsjFQ8miYNs
Content-Type: application/json

{
  "userId": "6533b70719c994f5a07a4b7c",
  "title": "The Tile House!",
  "description": "I am happy to welcome you to my apartment in the city center! Yo!",
  "previewImage": "https://13.design.pages.academy/static/hotel/3.jpg",
  "postDate": "2023-10-15T09:44:46.438Z",
  "city": {
    "name": "Brussels",
    "location": {
      "latitude": 50.846557,
      "longitude": 4.351697
    }
  },
  "isPremium": false,
  "type": "Apartment",
  "bedrooms": 2,
  "maxAdults": 2,
  "price": 222,
  "location": {
    "latitude": 48.85661,
    "longitude": 2.351499
  },
  "goods": [
    "Breakfast",
    "Washer"
  ],
  "photos": [ "https://13.design.pages.academy/static/hotel/2.jpg" ]
}

### Удаление предложения
DELETE http://localhost:5001/offers/6548e0facc8898e4387f2714 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAaHRtbGFjYWRlbXkucnUiLCJuYW1lIjoiS2VrcyIsImlkIjoiNjU0OGRlMmRjYzg4OThlNDM4N2YyNmVmIiwiaWF0IjoxNjk5Mjc0NTMzLCJleHAiOjE2OTk0NDczMzN9.IzH18psFqy4TxEWG4P3fvak6zB3-kBytIsjFQ8miYNs
Content-Type: application/json

### Получить список премиальных предложений города
GET http://localhost:5001/offers/premium/Brussels HTTP/1.1
Content-Type: application/json

### Загрузить изображения для объявления
POST http://localhost:5001/offers/6544f0440e50272e1c12f6e0/image HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAaHRtbGFjYWRlbXkucnUiLCJuYW1lIjoiS2VrcyIsImlkIjoiNjU0OGRlMmRjYzg4OThlNDM4N2YyNmVmIiwiaWF0IjoxNjk5Mjc0NTMzLCJleHAiOjE2OTk0NDczMzN9.IzH18psFqy4TxEWG4P3fvak6zB3-kBytIsjFQ8miYNs
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photos"; filename="paris.jpeg"
Content-Type: image/jpeg

< /Users/av/Downloads/paris.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
