# Отзывы
### Получить список отзывов
GET http://localhost:5001/reviews/6533b70719c994f5a07a4b7e HTTP/1.1
Content-Type: application/json
### Создание отзыва
POST http://localhost:5001/reviews HTTP/1.1
Content-Type: application/json

{
  "userId": "6533b70719c994f5a07a4b89",
  "offerId": "6533b70719c994f5a07a4b7e",
  "comment": "A place!!",
  "rating": 5
}
