export const CREATE_OFFER_RESTRICTIONS = {
  TITLE_MIN_LENGTH: 10,
  TITLE_MAX_LENGTH: 100,
  DESCRIPTION_MIN_LENGTH: 20,
  DESCRIPTION_MAX_LENGTH: 1024,
  PREVIEW_IMAGE_MAX_LENGTH: 256,
  BEDROOMS_MIN_VALUE: 1,
  BEDROOMS_MAX_VALUE: 8,
  MAX_ADULTS_MIN_VALUE: 1,
  MAX_ADULTS_MAX_VALUE: 10,
  PRICE_MIN_VALUE: 100,
  PRICE_MAX_VALUE: 100000,
};
